travis:
  secure:
    BINSTAR_TOKEN: owlcH+wD9Ctft7etLh9X1V4v9blkt9hHyVMyTi0ff+gbVz+cwz7JOvTh27y2kCKfbSGWRw/pTfchEG1HkizvzPy5NUWaxcmRYQCWq/uzg0ni6eqIvPQEyPJLbbSnG5ziWQJmFh484RT0dXh0DFdF/KQa1kjBJnRMaGq7ggwiXoTNV3R/qhc8CtGzismaKLAY7HMYVh0hWw51IQToHKI6s8RNmTJ9KKYKQb2CxIx67NTctmU+skASVFApC23XFJiqx3Cm0DnALGnpZAu09OaG98Jbl7qafxXVD5pYTkTwNEbzywKXvec9w1ixkHP2DVQhAsMLqHPy1n0akg2ZtBj9EZjW2npdE+t16ZPK6DhAs/5vJGBU1NjLONTNfrRMFXMBAJgmPbLmmDLsDfGpdWUQARfIp6uQBl9NO4pabSEtMwySDIinDyZYBF/WGOw5+O/Ic6z5iKBsvIDD1guMED2RR2M/09aXD2iYBGs5vqbNGVY3j7Q6wTWbMnZXOR2nTi5SHQWgxgpt+BjC3GKIVppc8sIbyFv/f6xBjCl7y/lNn/VktN0vMV/ro7Gp2UO+bIIBnpsYfLlIWwfBNXJSu+f0mJ2pkoNgwYzLqGxcdjI5GRcIooGkHlg+kG0LBUYLBxIHJqlAb2arP7VRqy1mWCjBJjBAZ8NDokSwoZRzzFwf7Pk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
