travis:
  secure:
    BINSTAR_TOKEN: oMoTYQxWtlnYH50I+aSLlX+MujPDL06p8f2/s57gCjmhFBF+ZrAI3xHBBc0hpKa5pytBkqxYV6Ivo1J4ZIxx1R1BkixWO0GH+nVn6OOmFkdRAgfEPcWTT+WPKfclvn6Uz4mhpoRKsooShDHxAnfo3kjBQpoNIpu331uQ/lEForAg034pR72A1FEQvhp/RzSqJ4cVdQ884NVAFwvggHDKljZzC7U3BbhiYuTjWSniqdO1zKnPrtqUsDVagcvljG922HPZvprvbQvQ8pYC4u1BVjV5b/QHMhIXc+El2KJfTK41/GCiKxzmLU76QQFHvxbGzV2JKUpwwUpzkoynLwxQwFa2LBXCaAN/RDASpmG0eMma4WVUZpamsAwujof8OwKf0kE0jmeMOirSRVaHL3rytOyWRNza0sWi9dpfqS6d+Z41lBbVKPtSLlph8wTGNRbhurB9SiVuUQVWVetJPdj9wXiE0Q8wHFoCLxKdLyy1OM0uUkoFEnaDPN1w4W24QsvTUudIhMIRYTPZprkDGJGymhpeUwuUNywpo3zy0jr12wqe7vtpUoqHX6t+p921RPgJg0MG+Q73EV0Ky3lyv1XomoiHcWmzTqLcpb/FBX5uwwUW9TIqSdTfY5m1kwjbaO23HuwteEn5Jzj7MauYYAsC5b/oQ9fC66UnZroPEC9JBY8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
